import { Context } from 'koishi';
export declare class RocomClient {
    private baseUrl;
    private apiKey;
    private timeout;
    private lastError;
    private lastErrorBrief;
    constructor(baseUrl: string, apiKey: string, timeout?: number);
    private sanitizeUid;
    private wegameHeaders;
    private rocomHeaders;
    private formatHttpError;
    private simplifyErrorMessage;
    private shouldRetryIngameWithApiKey;
    private isSensitiveLogKey;
    private maskSensitiveValue;
    private sanitizeForLog;
    private headersForLog;
    private stringifyForLog;
    private logRequestFailureDetails;
    private get;
    private post;
    private scopedParams;
    private delete;
    private requestWithStatus;
    private requestIngameWithFallback;
    private getIngameTask;
    qqQrLogin(ctx: Context, userIdentifier: string): Promise<any>;
    qqQrStatus(ctx: Context, fwToken: string, userIdentifier: string): Promise<any>;
    wechatQrLogin(ctx: Context, userIdentifier: string): Promise<any>;
    wechatQrStatus(ctx: Context, fwToken: string, userIdentifier: string): Promise<any>;
    importToken(ctx: Context, tgpId: string, tgpTicket: string, userIdentifier: string): Promise<any>;
    createBinding(ctx: Context, fwToken: string, userIdentifier: string): Promise<any>;
    refreshBinding(ctx: Context, bindingId: string, userIdentifier: string): Promise<any>;
    deleteBinding(ctx: Context, bindingId: string, userIdentifier: string): Promise<boolean>;
    getAccounts(ctx: Context, userIdentifier?: string, accountType?: number): Promise<any>;
    bindUid(ctx: Context, uid: string, userIdentifier?: string): Promise<any>;
    getRole(ctx: Context, fwToken: string, accountType?: number, userIdentifier?: string): Promise<any>;
    getEvaluation(ctx: Context, fwToken: string, userIdentifier?: string): Promise<any>;
    getLastError(defaultMessage?: string): string;
    getLastErrorBrief(defaultMessage?: string): string;
    private setLastError;
    getPetSummary(ctx: Context, fwToken: string, userIdentifier?: string): Promise<any>;
    getCollection(ctx: Context, fwToken: string, userIdentifier?: string): Promise<any>;
    getBattleOverview(ctx: Context, fwToken: string, userIdentifier?: string): Promise<any>;
    getBattleList(ctx: Context, fwToken: string, pageSize?: number, afterTime?: string, userIdentifier?: string): Promise<any>;
    private isIngamePlayerPayload;
    ingamePlayerSearch(ctx: Context, uid: string): Promise<any>;
    getPets(ctx: Context, fwToken: string, petSubset?: number, pageNo?: number, pageSize?: number, userIdentifier?: string): Promise<any>;
    getLineupList(ctx: Context, fwToken: string, pageNo?: number, category?: string, userIdentifier?: string): Promise<any>;
    getExchangePosters(ctx: Context, fwToken: string, pageNo?: number, userIdentifier?: string): Promise<any>;
    getMerchantInfo(ctx: Context, refresh?: boolean): Promise<any>;
    queryPetSize(ctx: Context, diameter: number, weight: number, sameRideEgg?: boolean, userIdentifier?: string): Promise<any>;
    getActivitiesInfo(ctx: Context, refresh?: boolean, userIdentifier?: string): Promise<any>;
    syncConfig(ctx: Context, userIdentifier?: string): Promise<any>;
    getAnnouncementList(ctx: Context, params?: {
        category_id?: number | string;
        page?: number;
        limit?: number;
        order?: string;
    }, userIdentifier?: string): Promise<any>;
    getLatestAnnouncement(ctx: Context, params?: {
        category_id?: number | string;
        order?: string;
    }, userIdentifier?: string): Promise<any>;
    getAnnouncementDetail(ctx: Context, threadId: number | string, userIdentifier?: string): Promise<any>;
    getEggSearch(ctx: Context, height: number, weight: number, pageNo?: number, pageSize?: number, userIdentifier?: string): Promise<any>;
    getEggGroups(ctx: Context, userIdentifier?: string): Promise<any>;
    getEggGroupPets(ctx: Context, groupIds: string | number[], matchMode?: 'any' | 'all', pageNo?: number, pageSize?: number, userIdentifier?: string): Promise<any>;
    getEggPetGroups(ctx: Context, query: string, limit?: number, userIdentifier?: string): Promise<any>;
    getEggExchanges(ctx: Context, params?: Record<string, any>, userIdentifier?: string): Promise<any>;
    postEggExchange(ctx: Context, data: Record<string, any>, userIdentifier?: string): Promise<any>;
    getMyEggExchanges(ctx: Context, params?: Record<string, any>, userIdentifier?: string): Promise<any>;
    getEggExchangeReviewStatus(ctx: Context, postId: string | number, userIdentifier?: string): Promise<any>;
    closeEggExchange(ctx: Context, postId: string | number, closeReason?: string, userIdentifier?: string): Promise<any>;
    createEggExchangeSubscription(ctx: Context, filters: Record<string, any>, userIdentifier?: string): Promise<any>;
    getEggExchangeSubscriptions(ctx: Context, userIdentifier?: string): Promise<any>;
    deleteEggExchangeSubscription(ctx: Context, subscriptionId: string | number, userIdentifier?: string): Promise<any>;
    getEggExchangeEvents(ctx: Context, subscriptionId: string | number, afterEventId?: string, limit?: number, userIdentifier?: string): Promise<any>;
    ingameHomeInfo(ctx: Context, uid: string, waitMs?: number): Promise<any>;
    ingameMerchantInfo(ctx: Context, shopId: string | number): Promise<any>;
    getFriendship(ctx: Context, fwToken: string, userIds: string, userIdentifier?: string): Promise<any>;
    getStudentState(ctx: Context, fwToken: string, accountType?: number, userIdentifier?: string): Promise<any>;
    getStudentPerks(ctx: Context, fwToken: string, area?: number, accountType?: number, userIdentifier?: string): Promise<any>;
    searchWikiPet(ctx: Context, query: string, limit?: number): Promise<any>;
    searchWikiSkill(ctx: Context, query: string, limit?: number): Promise<any>;
    getWikiPetDetail(ctx: Context, options: {
        id?: number;
        name?: string;
    }): Promise<any>;
}
